radio_neo_admin:
    resource: "@RadioNeoAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

radio_neo_front:
    resource: "@RadioNeoFrontBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
