<?php

namespace RadioNeo\DatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends DocumentRepository
{
    /**
     * Get query builder for all posts
     *
     * @param  string $letter
     * @return Builder
     */
    public function getAllQueryBuilder($letter = null)
    {
        $queryBuilder = $this->getDefaultQueryBuilder();

        if ($letter) {
            $queryBuilder
                ->field('name')->equals(new \MongoRegex(sprintf('/^%s/i', $letter)))
                ->sort('created_at', 'DESC')
            ;
        } else {
            $queryBuilder->sort('name', 'ASC');
        }

        return $queryBuilder;
    }

    /**
     * Gets default configured query builder
     *
     * @return Builder
     */
    private function getDefaultQueryBuilder()
    {
        $queryBuilder = $this->createQueryBuilder();

        return $queryBuilder;
    }
}
