<?php

namespace RadioNeo\DatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use RadioNeo\DatabaseBundle\Document\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends DocumentRepository
{
    /**
     * Finds categories that don't have children
     *
     * @return Category[]
     */
    public function getParentCategories()
    {
        $rootCategory = $this->createQueryBuilder()
            ->field('name')->equals(Category::ROOT_CATEGORY_NAME)
            ->getQuery()
            ->getSingleResult()
        ;

        if ($rootCategory) {
            return $rootCategory->getChildren();
        }

        return array();
    }
}
