<?php

namespace RadioNeo\DatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Doctrine\ODM\MongoDB\Query\Builder;

use RadioNeo\DatabaseBundle\Document\Category;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends DocumentRepository
{
    /**
     * Get query builder for all posts
     *
     * @param  Category $searchCategory
     * @return Builder
     */
    public function getAllQueryBuilder()
    {
        $queryBuilder = $this->getDefaultQueryBuilder();

        return $queryBuilder;
    }

    /**
     * Get query builder to get posts for given category and its children
     *
     * @param  Category $searchCategory
     * @return Builder
     */
    public function getByCategory(Category $searchCategory)
    {
        $queryBuilder = $this->getDefaultQueryBuilder();
        $queryBuilder->addOr($queryBuilder->expr()->field('category')->references($searchCategory));

        $categories = $searchCategory->getAllChildren();

        foreach ($categories as $category) {
            $queryBuilder->addOr($queryBuilder->expr()->field('category')->references($category));
        }

        return $queryBuilder;
    }

    /**
     * Gets default configured query builder
     *
     * @return Builder
     */
    private function getDefaultQueryBuilder()
    {
        $queryBuilder = $this->createQueryBuilder()->sort('publication_date', 'DESC');

        return $queryBuilder;
    }
}
