<?php

namespace RadioNeo\DatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use RadioNeo\DatabaseBundle\Document\Category;
use RadioNeo\DatabaseBundle\Document\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends DocumentRepository
{
    /**
     * Finds posts for given category and its children
     *
     * @param  Category $searchCategory
     * @return Post[]
     */
    public function getByCategory(Category $searchCategory)
    {
        $queryBuilder = $this->createQueryBuilder();
        $queryBuilder->addOr($queryBuilder->expr()->field('category')->references($searchCategory));

        $categories = $searchCategory->getAllChildren();

        foreach ($categories as $category) {
            $queryBuilder->addOr($queryBuilder->expr()->field('category')->references($category));
        }

        $posts = $queryBuilder->getQuery()->execute();

        return $posts;
    }
}
